services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn project_name.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: POETRY_VERSION
        value: 1.8.3
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: yourapp.onrender.com
